/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.tmsmod;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import net.mcreator.tmsmod.gui.GuiTrade1;
import net.mcreator.tmsmod.gui.GuiTerminalGUI;
import net.mcreator.tmsmod.gui.GuiT1GTravelGUI;
import net.mcreator.tmsmod.gui.GuiShredderGUI;
import net.mcreator.tmsmod.gui.GuiScam;
import net.mcreator.tmsmod.gui.GuiInfuserGUI;
import net.mcreator.tmsmod.gui.GuiGalacticTravelGUI;
import net.mcreator.tmsmod.gui.GuiGUIGrill;
import net.mcreator.tmsmod.gui.GuiFabricator;
import net.mcreator.tmsmod.gui.GuiDiskmakerGUI;
import net.mcreator.tmsmod.gui.GuiCatstarelol;
import net.mcreator.tmsmod.gui.GuiBackupT10GalacticGUI;

import java.util.function.Supplier;
import java.util.Random;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class ElementsTmsModMod implements IFuelHandler, IWorldGenerator {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	public final List<Supplier<Potion>> potions = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ElementsTmsModMod() {
		sounds.put(new ResourceLocation("tms_mod", "springandastorm"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "springandastorm")));
		sounds.put(new ResourceLocation("tms_mod", "corruptuniversesong"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "corruptuniversesong")));
		sounds.put(new ResourceLocation("tms_mod", "redgiantsong"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "redgiantsong")));
		sounds.put(new ResourceLocation("tms_mod", "intergalacticshippingsong"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "intergalacticshippingsong")));
		sounds.put(new ResourceLocation("tms_mod", "shinesong"), new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "shinesong")));
		sounds.put(new ResourceLocation("tms_mod", "getthisbred"), new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "getthisbred")));
		sounds.put(new ResourceLocation("tms_mod", "sussysong"), new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "sussysong")));
		sounds.put(new ResourceLocation("tms_mod", "manbehindtheslaughter"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "manbehindtheslaughter")));
		sounds.put(new ResourceLocation("tms_mod", "goodbyelulupt2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "goodbyelulupt2")));
		sounds.put(new ResourceLocation("tms_mod", "waterygraves"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "waterygraves")));
		sounds.put(new ResourceLocation("tms_mod", "fnaf3nightstart"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "fnaf3nightstart")));
		sounds.put(new ResourceLocation("tms_mod", "impesserdeth"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "impesserdeth")));
		sounds.put(new ResourceLocation("tms_mod", "lobbysong"), new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "lobbysong")));
		sounds.put(new ResourceLocation("tms_mod", "thunk"), new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "thunk")));
		sounds.put(new ResourceLocation("tms_mod", "youcouldbuyasaladglove"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "youcouldbuyasaladglove")));
		sounds.put(new ResourceLocation("tms_mod", "igetaround"), new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "igetaround")));
		sounds.put(new ResourceLocation("tms_mod", "ilylaa"), new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "ilylaa")));
		sounds.put(new ResourceLocation("tms_mod", "talldisc"), new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "talldisc")));
		sounds.put(new ResourceLocation("tms_mod", "aubertheme"), new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "aubertheme")));
		sounds.put(new ResourceLocation("tms_mod", "trilosong"), new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "trilosong")));
		sounds.put(new ResourceLocation("tms_mod", "susmiser"), new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "susmiser")));
		sounds.put(new ResourceLocation("tms_mod", "ourtheme"), new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "ourtheme")));
		sounds.put(new ResourceLocation("tms_mod", "monsterwhale"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tms_mod", "monsterwhale")));
	}

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == ElementsTmsModMod.ModElement.class)
					elements.add((ElementsTmsModMod.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ElementsTmsModMod.ModElement::initElements);
		this.addNetworkMessage(TmsModModVariables.WorldSavedDataSyncMessageHandler.class, TmsModModVariables.WorldSavedDataSyncMessage.class,
				Side.SERVER, Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = TmsModModVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = TmsModModVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				TmsModMod.PACKET_HANDLER.sendTo(new TmsModModVariables.WorldSavedDataSyncMessage(0, mapdata), (EntityPlayerMP) event.player);
			if (worlddata != null)
				TmsModMod.PACKET_HANDLER.sendTo(new TmsModModVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = TmsModModVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				TmsModMod.PACKET_HANDLER.sendTo(new TmsModModVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;
	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			TmsModMod.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}
	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiTerminalGUI.GUIID)
				return new GuiTerminalGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiTrade1.GUIID)
				return new GuiTrade1.GuiContainerMod(world, x, y, z, player);
			if (id == GuiScam.GUIID)
				return new GuiScam.GuiContainerMod(world, x, y, z, player);
			if (id == GuiCatstarelol.GUIID)
				return new GuiCatstarelol.GuiContainerMod(world, x, y, z, player);
			if (id == GuiInfuserGUI.GUIID)
				return new GuiInfuserGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiFabricator.GUIID)
				return new GuiFabricator.GuiContainerMod(world, x, y, z, player);
			if (id == GuiShredderGUI.GUIID)
				return new GuiShredderGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGalacticTravelGUI.GUIID)
				return new GuiGalacticTravelGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiBackupT10GalacticGUI.GUIID)
				return new GuiBackupT10GalacticGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGUIGrill.GUIID)
				return new GuiGUIGrill.GuiContainerMod(world, x, y, z, player);
			if (id == GuiDiskmakerGUI.GUIID)
				return new GuiDiskmakerGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiT1GTravelGUI.GUIID)
				return new GuiT1GTravelGUI.GuiContainerMod(world, x, y, z, player);
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiTerminalGUI.GUIID)
				return new GuiTerminalGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiTrade1.GUIID)
				return new GuiTrade1.GuiWindow(world, x, y, z, player);
			if (id == GuiScam.GUIID)
				return new GuiScam.GuiWindow(world, x, y, z, player);
			if (id == GuiCatstarelol.GUIID)
				return new GuiCatstarelol.GuiWindow(world, x, y, z, player);
			if (id == GuiInfuserGUI.GUIID)
				return new GuiInfuserGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiFabricator.GUIID)
				return new GuiFabricator.GuiWindow(world, x, y, z, player);
			if (id == GuiShredderGUI.GUIID)
				return new GuiShredderGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiGalacticTravelGUI.GUIID)
				return new GuiGalacticTravelGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiBackupT10GalacticGUI.GUIID)
				return new GuiBackupT10GalacticGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiGUIGrill.GUIID)
				return new GuiGUIGrill.GuiWindow(world, x, y, z, player);
			if (id == GuiDiskmakerGUI.GUIID)
				return new GuiDiskmakerGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiT1GTravelGUI.GUIID)
				return new GuiT1GTravelGUI.GuiWindow(world, x, y, z, player);
			return null;
		}
	}
	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ElementsTmsModMod elements;
		protected final int sortid;
		public ModElement(ElementsTmsModMod elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
